CREATE  DATABASE project;
use project;
CREATE TABLE Airport_details( id int,  a_name varchar(20),arrival_time bigint,departure_time bigint,price bigint);
CREATE TABLE Cricket_team(id int,t_name varchar(30),no_of_players varchar(10),captain varchar(40),coach varchar(50));
ALTER TABLE Airport_details ADD column airport_location varchar(20);
ALTER TABLE Airport_details ADD column  airport_id varchar(30);
ALTER TABLE Airport_details ADD column  flight_name varchar(20);
ALTER TABLE Airport_details RENAME column  a_name TO airport_name;
ALTER TABLE Airport_details RENAME column  arrival_time TO a_time;
ALTER TABLE Airport_details RENAME column  departure_time TO d_time;
ALTER TABLE Airport_details RENAME column  price TO cost;
ALTER TABLE Airport_details DROP column cost;
ALTER TABLE Airport_details modify column a_time int; 
ALTER TABLE Cricket_team ADD column team_location varchar(20);
ALTER TABLE Cricket_team ADD column  team_id varchar(30);
ALTER TABLE Cricket_team ADD column  team_identity varchar(20);
ALTER TABLE Cricket_team RENAME column  t_name TO team_name;
ALTER TABLE Cricket_team RENAME column  no_of_players TO p_name;
ALTER TABLE Cricket_team RENAME column  c_name TO captains;
ALTER TABLE Cricket_team DROP column coach;
ALTER TABLE Cricket_team modify column id bigint ; 
SELECT * FROM Cricket_team;
